export const queriesExtra = {
  sports: [
    "Best soccer players in the world [year]",
    "NBA playoffs predictions [year]",
    "How to improve running speed",
    "Best workout routines for beginners",
    "Top 10 tennis players [year]",
    "How to train for a marathon",
    "NFL Super Bowl predictions [year]",
    "Best sports nutrition tips",
    "How to improve basketball dribbling",
    "Top football clubs in the world [year]",
    "Best Olympic athletes of [year]",
    "How to build muscle fast",
    "Swimming techniques for beginners",
    "Best sports documentaries [year]",
    "How to recover from sports injuries",
    "Top golf courses in the world",
    "Best yoga poses for athletes",
    "How to increase stamina",
    "Top MMA fighters [year]",
    "Best cycling routes near me",
    "How to improve soccer shooting",
    "Top baseball players [year]",
    "How to train like a professional athlete",
    "Best CrossFit workouts",
    "How to improve flexibility",
    "Top cricket teams [year]",
    "Best home gym equipment [year]",
    "How to start boxing training",
    "Top F1 drivers [year]",
    "Best rugby teams in the world",
    "How to improve volleyball skills",
    "Top basketball drills for beginners",
    "Best sports shoes [year]",
    "How to prevent sports injuries",
    "Top swimmers in the world [year]",
    "Best hiking trails near me",
    "How to improve tennis serve",
    "Top sports coaches of all time",
    "Best gym supplements [year]",
    "How to do a proper squat",
    "Top extreme sports to try",
    "Best football tactics explained",
    "How to get better at golf",
    "Top sports scholarships [year]",
    "Best workout apps [year]",
    "How to train for triathlon",
    "Top sports stadiums in the world",
    "Best stretching routines",
    "How to get into professional sports",
    "Champions League results [year]",
    "World Cup highlights [year]",
    "Best sports medicine clinics",
    "How to improve swim technique",
    "Top sports nutrition brands",
    "Best boxing techniques for beginners",
    "How to get six pack abs",
    "Top women athletes [year]",
    "Best outdoor sports activities",
    "How to improve archery skills",
    "Top basketball shooting drills",
    "Best resistance band exercises",
    "How to increase vertical jump",
    "Top sports coaching certifications",
    "Best trail running shoes [year]",
    "How to improve endurance for sports",
    "Top youth sports leagues near me",
  ],
  food: [
    "Best restaurants near me",
    "How to make homemade pizza",
    "Easy dinner recipes for beginners",
    "Best healthy breakfast ideas",
    "How to bake sourdough bread",
    "Top 10 most popular cuisines",
    "Best vegetarian recipes [year]",
    "How to make sushi at home",
    "Easy pasta recipes",
    "Best dessert recipes",
    "How to make perfect scrambled eggs",
    "Top street food destinations",
    "Best keto diet recipes",
    "How to cook steak perfectly",
    "Easy Asian recipes for beginners",
    "Best smoothie recipes",
    "How to make chicken tikka masala",
    "Top comfort food recipes",
    "Best gluten-free recipes",
    "How to make French crepes",
    "Top brunch ideas",
    "Best meal prep ideas for the week",
    "How to make chocolate lava cake",
    "Best vegan recipes [year]",
    "How to make homemade ramen",
    "Top 10 superfoods",
    "Best salad recipes",
    "How to make guacamole",
    "Easy Mexican recipes",
    "Best burger recipes",
    "How to make croissants from scratch",
    "Top food trends [year]",
    "Best meal delivery services [year]",
    "How to make pad thai",
    "Top chocolate brands [year]",
    "Best air fryer recipes",
    "How to make cheesecake",
    "Top coffee brewing methods",
    "Best cocktail recipes",
    "How to make butter chicken",
    "Top wine and food pairings",
    "Best slow cooker recipes",
    "How to make homemade ice cream",
    "Top breakfast spots near me",
    "Best holiday cookie recipes",
    "How to make beef stew",
    "Top food documentaries [year]",
    "Best plant-based protein sources",
    "How to make spring rolls",
    "Top healthy snack ideas",
    "Best soup recipes for winter",
    "How to make tiramisu",
    "Top fermented foods benefits",
    "Best taco recipes",
    "How to make dim sum at home",
    "Top cheese varieties explained",
    "Best BBQ recipes",
    "How to make hollandaise sauce",
    "Best kitchen gadgets [year]",
    "How to reduce food waste at home",
    "Best instant pot recipes",
    "How to make croissant sandwiches",
    "Top farm-to-table restaurants [year]",
  ],
  health: [
    "How to boost immune system naturally",
    "Best exercises for weight loss",
    "How to improve mental health",
    "Best vitamins and supplements [year]",
    "How to get better sleep",
    "Top mental health apps [year]",
    "How to reduce stress",
    "Best diet plans [year]",
    "How to lower blood pressure naturally",
    "Top benefits of meditation",
    "How to improve gut health",
    "Best ways to stay hydrated",
    "How to build healthy habits",
    "Top signs of vitamin deficiency",
    "How to manage anxiety naturally",
    "Best foods for brain health",
    "How to improve posture",
    "Top benefits of walking daily",
    "How to detox your body naturally",
    "Best breathing exercises for stress",
    "How to improve heart health",
    "Top warning signs of diabetes",
    "How to lose belly fat",
    "Best natural remedies for headaches",
    "How to improve skin health",
    "Top benefits of yoga",
    "How to quit smoking",
    "Best foods for energy",
    "How to strengthen your immune system",
    "Top signs of depression",
    "How to improve eyesight naturally",
    "Best exercises for back pain",
    "How to manage chronic pain",
    "Top benefits of green tea",
    "How to improve memory",
    "Best ways to reduce inflammation",
    "How to maintain healthy weight",
    "Top foods that boost metabolism",
    "How to improve lung capacity",
    "Best stretches for flexibility",
    "How to improve cholesterol levels",
    "Top benefits of cold showers",
    "How to prevent heart disease",
    "Best natural sleep remedies",
    "How to improve bone density",
    "Top anti-aging foods",
    "How to reduce sugar intake",
    "Best exercises for seniors",
    "How to improve kidney health",
    "Top benefits of intermittent fasting",
    "How to manage blood sugar",
    "Best foods for liver health",
    "How to improve thyroid function",
    "Top signs of hormonal imbalance",
    "How to boost serotonin naturally",
    "Best ways to improve focus",
    "How to do mindfulness meditation",
    "Top health benefits of fasting",
    "Best probiotics for gut health",
    "How to prevent diabetes naturally",
    "Best morning routines for health",
    "How to reduce screen time effects",
    "Top longevity habits",
  ],
  finance: [
    "How to invest in stocks for beginners",
    "Best ways to save money",
    "How to create a budget",
    "Top investment strategies [year]",
    "How to pay off debt fast",
    "Best credit cards [year]",
    "How to build an emergency fund",
    "Top passive income ideas",
    "How to start investing with little money",
    "Best financial books [year]",
    "How to improve credit score",
    "Top cryptocurrency trends [year]",
    "How to save for retirement",
    "Best robo-advisors [year]",
    "How to negotiate salary",
    "Top dividend stocks [year]",
    "How to flip houses",
    "Best personal finance apps [year]",
    "How to create multiple income streams",
    "Top ETFs to invest in [year]",
    "How to reduce monthly expenses",
    "Best savings account rates [year]",
    "How to invest in real estate",
    "Top ways to make money online",
    "How to avoid financial mistakes",
    "Best tax saving strategies",
    "How to build wealth in your 30s",
    "Top index funds [year]",
    "How to start a side hustle",
    "Best insurance policies [year]",
    "How to manage student loans",
    "Top fintech companies [year]",
    "How to invest in gold",
    "Best budgeting methods",
    "How to achieve financial independence",
    "Top REITs to invest in [year]",
    "How to save money on groceries",
    "Best online banks [year]",
    "How to invest in bonds",
    "Top money saving challenges",
    "How to create a financial plan",
    "Best ways to earn extra income",
    "How to calculate net worth",
    "Top value stocks [year]",
    "How to protect finances during recession",
    "Best ways to invest 1000 dollars",
    "How to reduce tax burden legally",
    "Top growth stocks [year]",
    "How to save for house down payment",
    "Best financial advisors near me",
    "How to automate savings",
    "Top money management tips",
    "How to invest in mutual funds",
    "Best ways to earn passive income",
    "How to reduce credit card debt",
    "Top financial goals to set",
    "How to teach kids about money",
    "Best investment portfolios [year]",
    "How to diversify investments",
    "Top blockchain investments [year]",
    "Best frugal living tips",
    "How to understand compound interest",
    "Top wealth building books [year]",
  ],
  science: [
    "Latest space discoveries [year]",
    "How does DNA work",
    "Black holes explained simply",
    "Best science documentaries [year]",
    "How does the human brain work",
    "Latest climate change research",
    "How does quantum computing work",
    "Top scientific breakthroughs [year]",
    "How does CRISPR gene editing work",
    "Latest Mars mission updates",
    "How do vaccines work",
    "Top chemistry experiments at home",
    "How does nuclear fusion work",
    "Latest physics discoveries",
    "How does artificial intelligence learn",
    "Top biology facts",
    "How does the immune system work",
    "Latest astronomy news",
    "How does photosynthesis work",
    "Top psychology studies [year]",
    "How does gravity work",
    "Latest ocean discoveries",
    "How does evolution work",
    "Top neuroscience discoveries [year]",
    "How does climate change affect ecosystems",
    "Latest genetics research",
    "How does the nervous system work",
    "Top environmental science news",
    "How does sonar work",
    "Latest medical breakthroughs [year]",
    "How does the ozone layer protect Earth",
    "Top chemistry discoveries [year]",
    "How does earth's magnetic field work",
    "Latest renewable energy research",
    "How does dark matter work",
    "Top paleontology discoveries [year]",
    "How does the digestive system work",
    "Latest technology in medicine",
    "How does sound travel",
    "Top geology facts",
    "How does nuclear energy work",
    "Latest space telescope discoveries",
    "How does the water cycle work",
    "Top scientific journals [year]",
    "How does light travel",
    "Latest research on aging",
    "How do earthquakes form",
    "Top environmental breakthroughs [year]",
    "How does the carbon cycle work",
    "Latest findings about the universe",
    "How are stars formed",
    "What is dark energy",
    "How does the human eye work",
    "Top space missions [year]",
    "How does the earth rotate",
    "Latest biology research [year]",
    "How does radioactivity work",
    "Top scientific inventions of all time",
    "How does the moon affect tides",
    "Latest chemistry breakthroughs",
  ],
  gaming: [
    "Best PC games [year]",
    "Top RPG games to play",
    "How to improve gaming skills",
    "Best gaming headsets [year]",
    "Top open world games [year]",
    "How to build a gaming PC",
    "Best gaming chairs [year]",
    "Top survival games [year]",
    "How to reduce gaming lag",
    "Best multiplayer games [year]",
    "Top FPS games [year]",
    "How to stream on Twitch",
    "Best gaming monitors [year]",
    "Top strategy games [year]",
    "How to get better at chess",
    "Best indie games [year]",
    "Top esports tournaments [year]",
    "How to join esports team",
    "Best gaming keyboards [year]",
    "Top horror games [year]",
    "How to improve reaction time for gaming",
    "Best mobile games [year]",
    "Top simulation games [year]",
    "How to fix game crashes",
    "Best gaming mice [year]",
    "Top adventure games [year]",
    "How to earn money from gaming",
    "Best co-op games [year]",
    "Top puzzle games [year]",
    "How to optimize PC for gaming",
    "Best Nintendo Switch games [year]",
    "Top PlayStation games [year]",
    "How to get free games online",
    "Best Xbox games [year]",
    "Top fighting games [year]",
    "How to build gaming setup on budget",
    "Best VR games [year]",
    "Top racing games [year]",
    "How to get sponsored in esports",
    "Best story-driven games [year]",
    "Top retro games to play",
    "How to reduce eye strain while gaming",
    "Best educational games [year]",
    "Top sports video games [year]",
    "How to backup game saves",
    "Best game streaming services [year]",
    "Top sandbox games [year]",
    "How to get better at Valorant",
    "Best action RPG games [year]",
    "Top MMO games [year]",
    "How to set up gaming room",
    "Best card games online [year]",
    "Top tactical shooter games [year]",
    "How to record gameplay on PC",
    "Best battle royale games [year]",
    "Top city-building games [year]",
    "How to choose gaming laptop",
    "Best controller for PC gaming",
    "Top most anticipated games [year]",
    "How to get game development job",
    "Best gaming desk setup [year]",
    "Top Nintendo exclusives [year]",
    "How to reduce input lag in gaming",
  ],
  nature: [
    "Most beautiful national parks in the world",
    "How to identify bird species",
    "Best wildlife destinations [year]",
    "How to start birdwatching",
    "Top rainforests to visit",
    "How does coral reef form",
    "Best nature documentaries [year]",
    "How to start hiking",
    "Top endangered species [year]",
    "How does a volcano form",
    "Best stargazing locations",
    "How to identify tree species",
    "Top ocean creatures facts",
    "How does lightning form",
    "Best waterfalls in the world",
    "How to survive in the wilderness",
    "Top deserts to visit",
    "How does a tornado form",
    "Best mountain ranges to explore",
    "How to identify wild plants",
    "Top caves to visit around the world",
    "How do northern lights form",
    "Best nature photography tips",
    "How to set up wildlife camera",
    "Top river systems in the world",
    "How do glaciers form",
    "Best snorkeling destinations",
    "How to identify animal tracks",
    "Top forests to visit",
    "How does an earthquake happen",
    "Best nature reserves near me",
    "How to go off-grid living",
    "Top wetlands in the world",
    "How does seasons change happen",
    "Best whale watching spots",
    "How to build a birdhouse",
    "Top volcanic islands to visit",
    "How does a rainbow form",
    "Best eco-tourism destinations [year]",
    "How to identify cloud types",
    "Top tidal pools facts",
    "How does wind form",
    "Best butterfly gardens",
    "How to grow a native plant garden",
    "Top geothermal wonders",
    "How does permafrost affect climate",
    "Best places to see wildlife",
    "How to reduce carbon footprint",
    "Top nature trails near me",
    "How do fireflies produce light",
    "Best camping spots near me",
    "How to identify mushroom species safely",
    "Top tide pools to visit",
    "How do tectonic plates move",
    "Best wildflower spots near me",
    "How to compost at home",
    "Top rewilding projects in the world",
    "How do animals migrate",
    "Best rock formations in the world",
    "How to find fossils",
  ],
  history: [
    "Ancient Rome facts",
    "How did World War 2 start",
    "Egyptian pyramids mysteries",
    "History of the Roman Empire",
    "How did the Cold War end",
    "Ancient Greece civilization facts",
    "History of the United States",
    "How did the Renaissance begin",
    "Ancient Mayan civilization facts",
    "History of the British Empire",
    "How did World War 1 start",
    "Ancient Egyptian history",
    "History of China dynasties",
    "How did communism collapse",
    "Aztec civilization facts",
    "History of the Ottoman Empire",
    "How did the French Revolution start",
    "Viking history and culture",
    "History of ancient Japan",
    "How did slavery end in America",
    "Medieval castle facts",
    "History of the Byzantine Empire",
    "How did the Industrial Revolution change society",
    "Ancient Indian civilizations",
    "History of Alexander the Great",
    "How did colonialism affect Africa",
    "Mesopotamian civilization facts",
    "History of the Russian Revolution",
    "How did the Silk Road work",
    "Ancient Chinese inventions",
    "History of the Mongol Empire",
    "How did democracy begin in ancient Greece",
    "History of the crusades",
    "Ancient Inca civilization facts",
    "History of the Spanish Empire",
    "How did the American Civil War start",
    "History of the Islamic Golden Age",
    "Ancient Persian Empire facts",
    "History of Napoleon Bonaparte",
    "How did the Roman Republic fall",
    "History of the Han Dynasty",
    "Ancient Phoenician civilization facts",
    "History of the Mughal Empire",
    "How did apartheid end in South Africa",
    "History of the Mali Empire",
    "Ancient Carthage civilization",
    "History of the Ming Dynasty",
    "History of space exploration",
    "Cold War nuclear arms race facts",
    "History of women's suffrage movement",
    "Medieval knights and chivalry",
    "History of the printing press",
    "Ancient Sumerian civilization",
    "History of piracy golden age",
    "How did the Berlin Wall fall",
    "History of the internet",
    "Ancient Nubian civilization facts",
    "History of the Silk Road",
    "How did colonialism shape the modern world",
    "History of the Renaissance art",
  ],
  vietnam: [
    "phở bò ngon nhất Hà Nội",
    "bún chả Hà Nội địa chỉ nổi tiếng",
    "cách làm bánh mì Sài Gòn",
    "du lịch Đà Lạt [year]",
    "khách sạn view đẹp Đà Lạt [year]",
    "địa điểm check in Hội An",
    "bãi biển đẹp nhất Nha Trang",
    "tour Phú Quốc 3 ngày 2 đêm",
    "vé máy bay giá rẻ đi Sài Gòn [year]",
    "thời tiết Hà Nội tuần này",
    "chỉ số AQI Hà Nội hôm nay",
    "giá vàng hôm nay Việt Nam",
    "tỷ giá USD VND hôm nay",
    "lãi suất ngân hàng [year]",
    "cách đăng ký thẻ tín dụng online",
    "vay mua nhà lãi suất thấp [year]",
    "cách tiết kiệm tiền hiệu quả",
    "kinh nghiệm đầu tư chứng khoán cho người mới",
    "cách nấu cơm tấm Sài Gòn",
    "món ăn vặt Sài Gòn nên thử",
    "quán cà phê đẹp ở Đà Lạt",
    "review laptop học lập trình [year]",
    "laptop dưới 15 triệu tốt nhất [year]",
    "cách học tiếng Anh hiệu quả tại nhà",
    "khóa học lập trình Python miễn phí",
    "cách giảm cân an toàn trong 1 tháng",
    "bài tập yoga cho người mới bắt đầu",
    "thực đơn eat clean 7 ngày",
    "cách chăm sóc da mụn tại nhà",
    "vitamin nên uống hàng ngày",
    "review điện thoại tầm trung [year]",
    "so sánh iPhone và Samsung [year]",
    "cách tăng tốc WiFi tại nhà",
    "game mobile hay nhất [year]",
    "phim Việt Nam hay [year]",
    "phim Hàn đang hot [year]",
    "lịch thi đấu V League [year]",
    "kết quả bóng đá Việt Nam hôm nay",
    "tin tức công nghệ Việt Nam [year]",
    "startup Việt Nam nổi bật [year]",
    "việc làm IT tại Hà Nội [year]",
    "mức lương lập trình viên Việt Nam [year]",
    "cách làm CV xin việc chuẩn",
    "kinh nghiệm phỏng vấn xin việc IT",
    "địa điểm picnic gần Sài Gòn",
    "cắm trại gần Hà Nội cuối tuần",
    "cách trồng rau sạch tại nhà",
    "chăm sóc cây cảnh trong nhà",
    "thời trang công sở nữ [year]",
    "outfit đi chơi cuối tuần",
    "cách mix đồ basic đẹp",
    "nhạc Việt hay nhất [year]",
    "playlist chill học bài",
    "cách dọn nhà nhanh gọn",
    "mẹo vệ sinh bếp hiệu quả",
    "review máy hút bụi [year]",
    "cách chọn quạt điều hòa [year]",
    "tiết kiệm điện mùa hè",
    "địa điểm ăn lẩu ngon Hà Nội",
    "quán bún bò Huế nổi tiếng",
    "cách làm gỏi cuốn tôm thịt",
  ],
};
